    // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebInfos.Model
{
    [Table("Tb_departamento")]
    public partial class TbDepartamento
    {
        [Key]
        [Display(Name = "Código")]
        [Column("id_dep")]
        public int IdDep { get; set; }
        [Column("departamento")]
        [StringLength(50)]
        [Unicode(false)]
        public string Departamento { get; set; }
    }
}