// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebInfos.Model
{
    [Table("Tb_evento")]
    public partial class TbEvento
    {
        [Key]
        [Column("id_eve")]
        [Display(Name = "Código")]
        public int IdEve { get; set; }

        [Column("evento")]
        [StringLength(500)]
        [Unicode(false)]
        public string Evento { get; set; }
    }
}