// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebInfos.Model
{
    [Table("Tb_funcionario")]
    public partial class TbFuncionario
    {
        [Key]
        [Column("id_func")]
        [Display(Name = "Código")]
        public int IdFunc { get; set; }

        [Column("departamento")]
        [Required(ErrorMessage = "Informe o departamento")]
        public int? Departamento { get; set; }

        [Column("nome")]
        [StringLength(50)]
        [Unicode(false)]
        [Required(ErrorMessage = "Nome inválido")]
        public string Nome { get; set; }

        [Column("email")]
        [StringLength(50)]
        [Unicode(false)]
        [Display(Name = "E-mail")]
        [Required(ErrorMessage = "E-mail inválido")]
        public string Email { get; set; }

        [Column("telefone")]
        [Required(ErrorMessage = "Número inválido")]
        [StringLength(50)]
        [Unicode(false)]
        public string Telefone { get; set; }

    }
}