// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebInfos.Model
{
    [Table("Tb_noticia")]
    public partial class TbNoticia
    {
        [Key]
        [Column("id_not")]
        [Display(Name = "Código")]
        public int IdNot { get; set; }

        [Column("noticia")]
        [StringLength(500)]
        [Unicode(false)]
        [Display(Name = "Notícia")]
        [Required(ErrorMessage = "Informe a notícia")]
        public string Noticia { get; set; }
    }
}